--- #YAML:1.0
name: DBIx-HTML-LinkedMenus
version: 1.07
author:
  - Ron Savage <ron@savage.net.au>
abstract: Convert SQL to 2 linked HTML popup menus.
license: artistic
requires:
  Carp: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides:
  DBIx::HTML::LinkedMenus:
    file: lib/DBIx/HTML/LinkedMenus.pm
    version: 1.07
generated_by: Module::Build version 0.2607
