--- #YAML:1.0
name: DBIx-HTML-LinkedMenus
version: 1.06
author:
  - Ron Savage <ron@savage.net.au>
abstract: Convert SQL to 2 linked HTML popup menus.
license: artistic
requires:
  Carp: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides: {}
generated_by: Module::Build version 0.24
